#!/bin/bash
#Just a simple bash script to facilitate remote git directory creation from a local directory
{    
	echo "enter github or bitbucket:"
    read githubOrBitbucket   
    
    if [ $githubOrBitbucket = "github" ]
		then
			echo "GitHub Selected"  
	fi 
	if [ $githubOrBitbucket = "bitbucket" ]
		then	
			echo "BitBucket Selected"  
    fi   
	 
    echo "enter a valid git username:"
    read username
    #only used in bitbucket dir creation cURL command
    echo "enter a valid git password:"
    read -s password
    echo "enter a valid project name: (as in 'MyProject')"
    read projectname
    echo "enter valid path to our project directory: (as in '~/Myproject')"
    read projectdir
    #cannot cd into dir since we're in a subshell, so pretend we are typing at the terminal: $ eval cd "~/..."
    eval cd "$projectdir"
    rm -rf .git/
    pwd
    echo "enter commit message:"
    read commitmessage
             
   
    echo "Start - Creating remote Git Directory named '$projectname'"
    
    echo "Initializing Repo $projectname locally"
    git init
    
    echo "Add all files of the directory we are to Repo"
    git add *
    git status
    echo "Commit any changes to Repo"
    git commit -m "$commitmessage"
    git status
    echo "Create Repo $projectname on the remote server"
    
    if [ $githubOrBitbucket = "github" ]
		then			
			curl -u "$username" https://api.github.com/user/repos -d '{"name":"'$projectname'"}'
	fi
	if [ $githubOrBitbucket = "bitbucket" ]
		then	
			echo "CURLING $password"
			curl --user $username:$password https://api.bitbucket.org/1.0/repositories/ --data name=$projectname --data is_private='true'
			
    fi
    
    echo "Enter alias for the remote repository : (such as 'origin')"
    read origin
    echo "Make sure there's no alias named $origin"    
    git remote rm $origin
    git remote -v
    
    if [ $githubOrBitbucket = "github" ]
		then
			echo "Connect alias $origin to url repo: git@github.com:$username/$projectname.git"  
	fi
	if [ $githubOrBitbucket = "bitbucket" ]
		then
			echo "CONNECTING.."	
			echo "Connect alias $origin to url repo:  git@bitbucket.org:$username/$projectname.git"  
    fi
      
    if [ $githubOrBitbucket = "github" ]
		then			
			git remote add origin git@github.com:$username/$projectname.git
	fi
	if [ $githubOrBitbucket = "bitbucket" ]
		then			
			echo "REMOTE ADDING.."	
			git remote add origin https://$username@bitbucket.org/$username/$projectname.git
    fi
    
    
    echo "push changes across to remote server"    
    git push -u origin master
        
    if [ $githubOrBitbucket = "github" ]
		then
			echo "Finished - Creating remote Git Directory named 'git@github.com:$username/$projectname.git'"
	fi
	if [ $githubOrBitbucket = "bitbucket" ]
		then
			echo "Finished - Creating remote Git Directory named 'git@bitbucket.com:$username/$projectname.git'"
    fi
    
}

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
#  repo_name=$1
 
#  dir_name=`basename $(pwd)`
 
#  if [ "$repo_name" = "" ]; then
#    echo "Repo name (hit enter to use '$dir_name')?"
#    read repo_name
#  fi
 
#  if [ "$repo_name" = "" ]; then
#    repo_name=$dir_name
#  fi
 
#  username=`git config github.user`
#  if [ "$username" = "" ]; then
#    echo "Could not find username, run 'git config --global github.user <username>'"
#    invalid_credentials=1
#  fi
 
#  token=`git config github.token`
#  if [ "$token" = "" ]; then
#    echo "Could not find token, run 'git config --global github.token <token>'"
#    invalid_credentials=1
#  fi
 
#  if [ "$invalid_credentials" == "1" ]; then
#    return 1
#  fi
 
#  echo -n "Creating Github repository '$repo_name' ..."
#  curl -u "$username:$token" https://api.github.com/user/repos -d '{"name":"'$repo_name'"}' > /dev/null 2>&1
#  echo " done."
 
#  echo -n "Pushing local code to remote ..."
#  git remote add origin git@github.com:$username/$repo_name.git > /dev/null 2>&1
#  git push -u origin master > /dev/null 2>&1
#  echo " done."
